### ISSUE TITLE
Disable auto-shutoff functionality on scale

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#17]

**Comment by dsgorthy** [comment]
As described in Issue #7 , the scale automatically turns off after 3 minutes after the last weight change. The method in the user manual is not working.

**Comment by JackDinkel** [comment]
I did some research, people online claim to have called the manufacturer and asked about the auto-off feature. It sounds like the manual is general, and that feature does not apply to our particular product.

So, it sounds like there is no way around this with this scale. Yay. We can discuss at our next meeting, but since this is only a tech demo, I recommend we just live with it.
