### ISSUE TITLE
Error handling for sensor drivers

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#18]

**Comment by dsgorthy** [comment]
Each sensor driver will need more verbose error-handling. Current thoughts on this are 

- Verbose stderr/stdout logs from the sensor
- Ability to detect errors (for future notification functionality)

**Comment by JackDinkel** [comment]
Error code pushed to index.js.

The general idea I went with is this:
1. Check all data and sensor inputs for expected formatting.
2. Check all readings to ensure they are inside a specific range.
3. If a check fails, log an error, but do nothing. Do not invoke the stub drivers. Do not log any data to the database or backup csv. Do not pass go. Do not collect $200.

The stub drivers are now for development purposes only, as it does not make sense to ever log a fake value, except in development/testing. To activate the stub drivers, just set the appropriate `stub_drivers_on` variable at the top of index.js to `true`, and the fake drivers will be called instead of the real ones, and pesky error checking will be avoided. When the variables are set to false, it is assumed the sensors are plugged in and working, and errors will be thrown if they are not.

Future notifications or additional error handling should be able to be easily tacked on.

**Comment by JackDinkel** [comment]
Awaiting code review. Code is in the error_handling branch.

**Comment by JackDinkel** [comment]
I have merged the `snow-depth` branch from #21 into the `error_handling` branch for this ticket. I would prefer @dsgorthy to review both the new error handling code and his changes for #21 to make sure everything was ported over properly. When that is done, this should be good to merge into master.

I also added some basic bounds checking for the new snow_depth value.

**Comment by dsgorthy** [comment]
I'll be reviewing this tonight on my machine to verify changes.

**Comment by JackDinkel** [comment]
Complete and merged.
