### ISSUE TITLE
Research and develop weight to snow depth formula

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#21]

**Comment by dsgorthy** [comment]
1.25 lbs per inch

**Comment by dsgorthy** [comment]
Code developed and tested, pushed to the ```snow-depth``` branch. Awaiting code review.

**Comment by JackDinkel** [comment]
Reviewed.

I merged this into my branch `error_handling` (see #18) instead of master so that we can avoid pesky merge issues later on. It was fairly pesky to merge the two as is, but I think I have ported everything over to the new format correctly.

This now exists in `error_handling` inside #18. I will delete the `snow-depth` branch.
