### ISSUE TITLE
Scale Integration

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#7]
Description: Connect pressure plate to BITS

**Comment by dsgorthy** [comment]
Currently waiting on delivery of pressure plate. Nic will bring up to Boulder when it arrives.

**Comment by JackDinkel** [comment]
I have successfully written a python driver that can pull data from the scale on Linux!
The code is currently on the branch `scale_driver`.

**Comment by JackDinkel** [comment]
Unfortunately, the scale we bought has a wonderful "feature" called `auto shut-off`. According to the literature, there is a way to disable auto shut-off by pressing a key combination _every single time you turn on the device_. Of course, this key combo didn't work for me, so currently, the scale will shut off after 3 minutes of inactivity.
Workaround: pull data from it more often than every 3 minutes.

Also, it has another "feature" that zeros the weight on a restart, so even if there was 50 lbs on it, it would say zero.

Since this is just a tech demo, and the scale can't survive under snow conditions anyway, I suppose all this is fine, but FYI, kinda annoying.

**Comment by dsgorthy** [comment]
@JackDinkel and I have tested the driver code and confirmed that it is working. Closing out this task now, but opening up a new "housekeeping" issue for disabling the auto-shutoff feature of the scale. The method described in the user manual is not working for our scale.
